export interface StudioGame {
  game_id: number;
  game_uid: string;
  name: string;
  provider: string;
  category: string;
  rtp: number;
  max_multiplier: number;
  logo: string | null;
  thumbnail: string;
  description: string;
  isFeatured?: boolean;
}

export const STUDIO_GAMES: StudioGame[] = [
  {
    game_id: 88801,
    game_uid: "royal_skyrush",
    name: "Sky Rush",
    provider: "Royal Games Studio",
    category: "Crash / Multiplier",
    rtp: 97.5,
    max_multiplier: 1000.0,
    logo: null,
    thumbnail: "/games/royal_skyrush.svg",
    description: "Futuristic high-speed aerial flight machine. Watch the multiplier ascend and cash out before the supersonic sonic boom!",
    isFeatured: true,
  },
  {
    game_id: 88802,
    game_uid: "royal_tigertrail",
    name: "Tiger Trail",
    provider: "Royal Games Studio",
    category: "Step / Cashout",
    rtp: 98.0,
    max_multiplier: 500.0,
    logo: null,
    thumbnail: "/games/royal_tigertrail.svg",
    description: "Navigate the wild jungle stepping stones with the majestic tiger. Step forward for higher multipliers or cash out!",
    isFeatured: true,
  },
  {
    game_id: 88803,
    game_uid: "royal_bombgrid",
    name: "Bomb Grid",
    provider: "Royal Games Studio",
    category: "Originals / Mines",
    rtp: 98.5,
    max_multiplier: 500.0,
    logo: null,
    thumbnail: "/games/royal_bombgrid.svg",
    description: "5x5 energy grid minefield. Uncover glowing crystals and cash out before triggering a bomb!",
    isFeatured: true,
  },
  {
    game_id: 88804,
    game_uid: "royal_dropx",
    name: "Drop X",
    provider: "Royal Games Studio",
    category: "Physics / Plinko",
    rtp: 98.2,
    max_multiplier: 1000.0,
    logo: null,
    thumbnail: "/games/royal_dropx.svg",
    description: "Precision physics multiplier ball drop through metallic peg pins into high-reward jackpot buckets.",
    isFeatured: true,
  },
  {
    game_id: 88805,
    game_uid: "royal_cricketblast",
    name: "Cricket Blast",
    provider: "Royal Games Studio",
    category: "Crash / Sports",
    rtp: 97.6,
    max_multiplier: 500.0,
    logo: null,
    thumbnail: "/games/royal_cricketblast.svg",
    description: "Night stadium cricket hit. Batter smashes the ball into the night sky as multiplier escalates before catch.",
    isFeatured: true,
  },
  {
    game_id: 88806,
    game_uid: "royal_infinityx",
    name: "Infinity X",
    provider: "Royal Games Studio",
    category: "Limbo / Fast",
    rtp: 98.8,
    max_multiplier: 10000.0,
    logo: null,
    thumbnail: "/games/royal_infinityx.svg",
    description: "Ultra-fast target multiplier game. Target up to 10,000x and blast through the infinite energy portal.",
    isFeatured: true,
  },
  {
    game_id: 88807,
    game_uid: "royal_treasuretower",
    name: "Treasure Tower",
    provider: "Royal Games Studio",
    category: "Tower / Risk",
    rtp: 98.0,
    max_multiplier: 500.0,
    logo: null,
    thumbnail: "/games/royal_treasuretower.svg",
    description: "Climb the ancient 8-floor temple tower. Pick safe stone chests to unlock higher floors and legendary treasures.",
    isFeatured: false,
  },
  {
    game_id: 88808,
    game_uid: "royal_dicex",
    name: "Dice X",
    provider: "Royal Games Studio",
    category: "Probability / Dice",
    rtp: 99.0,
    max_multiplier: 990.0,
    logo: null,
    thumbnail: "/games/royal_dicex.svg",
    description: "Sleek 3D isometric dice probability table with roll over/under slider and real-time win probability feedback.",
    isFeatured: false,
  },
  {
    game_id: 88809,
    game_uid: "royal_cardclimb",
    name: "Card Climb",
    provider: "Royal Games Studio",
    category: "Cards / Hi-Lo",
    rtp: 98.3,
    max_multiplier: 120.0,
    logo: null,
    thumbnail: "/games/royal_cardclimb.svg",
    description: "Luxury card prediction table. Predict whether the next dealt card is Higher or Lower to climb the payout multiplier.",
    isFeatured: false,
  },
  {
    game_id: 88810,
    game_uid: "royal_luckywheel",
    name: "Lucky Wheel X",
    provider: "Royal Games Studio",
    category: "Wheel / Game Show",
    rtp: 97.0,
    max_multiplier: 100.0,
    logo: null,
    thumbnail: "/games/royal_luckywheel.svg",
    description: "High-octane casino money wheel with 97.0% RTP, mechanical pointer flick, and grand 100x Crown Jackpot.",
    isFeatured: false,
  },
];
